swagger: "2.0"
info:
  version: "1.0.0"
  title: Syscoin API
host: localhost:8000
basePath: /
schemes:
  # remove http to make production-grade
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /getinfo:
    x-swagger-router-controller: rpc
    get:
      operationId: getinfo
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Info"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /getmininginfo:
      x-swagger-router-controller: rpc
      get:
        operationId: getmininginfo
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/MiningInfo"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"

  /getpeerinfo:
      x-swagger-router-controller: rpc
      get:
        operationId: getpeerinfo
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/PeerInfoResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"

  /validateaddress:
      x-swagger-router-controller: rpc
      get:
        operationId: validateaddress
        parameters:
        - name: syscoinaddress
          in: query
          required: true
          type: string
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/ValidateAddressResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"

  /verifymessage:
    x-swagger-router-controller: rpc
    get:
      operationId: verifymessage
      parameters:
      - name: syscoinaddress
        in: query
        required: true
        type: string
      - name: signature
        in: query
        required: true
        type: string
      - name: message
        in: query
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: boolean
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /addmultisigaddress:
    x-swagger-router-controller: rpc
    get:
      operationId: addmultisigaddress
      parameters:
      - name: nrequired
        in: query
        required: true
        type: number
      - name: keysobject
        in: query
        required: false
        type: string
      - name: account
        in: query
        required: false
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /aliasaffiliates:
    x-swagger-router-controller: rpc
    get:
      operationId: aliasaffiliates
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              type: object #TODO: define type
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /aliasfilter:
    x-swagger-router-controller: rpc
    get:
      operationId: aliasfilter
      parameters:
      - name: regexp
        in: query
        description: apply [regexp] on aliases, empty means all aliases
        required: true
        type: string
      - name: maxage
        in: query
        description: look in last [maxage] blocks
        required: false
        type: number
      - name: from
        in: query
        description: show results from number [from]
        required: false
        type: number
      - name: nb
        in: query
        description: show [nb] results, 0 means all
        required: false
        type: number
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/AliasListEntry"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /aliashistory:
    x-swagger-router-controller: rpc
    get:
      operationId: aliashistory
      parameters:
      - name: aliasname
        in: query
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/AliasHistoryEntry"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /aliasinfo:
    x-swagger-router-controller: rpc
    get:
      operationId: aliasinfo
      parameters:
      - name: aliasname
        in: query
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Alias"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /aliaslist:
    x-swagger-router-controller: rpc
    get:
      operationId: aliaslist
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/AliasListEntry"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /aliasnew:
    x-swagger-router-controller: rpc
    get:
      operationId: aliasnew
      parameters:
      - name: aliasname
        in: query
        required: true
        type: string
      - name: publicvalue
        in: query
        required: true
        type: string
      - name: privatevalue
        in: query
        required: false
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /aliasscan:
    x-swagger-router-controller: rpc
    get:
      operationId: aliasscan
      parameters:
      - name: start-name
        in: query
        required: false
        type: string
      - name: max-returned
        in: query
        required: false
        type: number
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              type: string #TODO: could not execute RPC command, error'd
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /aliasupdate:
    x-swagger-router-controller: rpc
    get:
      operationId: aliasupdate
      parameters:
      - name: aliasname
        in: query
        required: true
        type: string
      - name: publicvalue
        in: query
        required: true
        type: string
      - name: privatevalue
        in: query
        required: false
        type: string
      - name: toalias_pubkey
        in: query
        required: false
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /certfilter:
    x-swagger-router-controller: rpc
    get:
      operationId: certfilter
      parameters:
      - name: regexp
        in: query
        description: apply [regexp] on certes, empty means all certes
        required: false
        type: string
      - name: maxage
        in: query
        description: look in last [maxage] blocks
        required: false
        type: string
      - name: from
        in: query
        description: show results from number [from]
        required: false
        type: string
      - name: nb
        in: query
        description: show [nb] results, 0 means all
        required: false
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/CertListEntry"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /certhistory:
    x-swagger-router-controller: rpc
    get:
      operationId: certhistory
      parameters:
      - name: certname
        in: query
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/CertHistoryEntry"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /certinfo:
    x-swagger-router-controller: rpc
    get:
      operationId: certinfo
      parameters:
      - name: certname
        in: query
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Cert"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /certlist:
    x-swagger-router-controller: rpc
    get:
      operationId: certlist
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/CertListEntry"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /certnew:
    x-swagger-router-controller: rpc
    get:
      description: Requires wallet passphrase to be set with walletpassphrase call.
      operationId: certnew
      parameters:
      - name: alias
        in: query
        description: An alias you own.
        required: true
        type: string
      - name: title
        in: query
        description: title, 255 bytes max.
        required: true
        type: string
      - name: data
        in: query
        description: data, 1KB max.
        required: false
        type: string
      - name: private
        in: query
        description: set to 1 if you only want to make the cert data private, only the owner of the cert can view it. Off by default.
        required: false
        type: boolean
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /certscan:
    x-swagger-router-controller: rpc
    get:
      operationId: certscan
      parameters:
      - name: start-cert
        in: query
        required: false
        type: string
      - name: max-returned
        in: query
        required: false
        type: number
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              type: string #TODO: could not execute RPC command, error'd
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /certtransfer:
    x-swagger-router-controller: rpc
    get:
      operationId: certtransfer
      parameters:
      - name: certkey
        in: query
        required: true
        type: string
      - name: alias
        in: query
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              type: string #TODO: assuming this returns array of txid related strings, check
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /certupdate:
    x-swagger-router-controller: rpc
    get:
      operationId: certupdate
      parameters:
      - name: guid
        in: query
        required: true
        type: string
      - name: title
        in: query
        required: true
        type: string
      - name: data
        in: query
        required: true
        type: string
      - name: private
        in: query
        required: true
        type: boolean
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /dumpprivkey:
    x-swagger-router-controller: rpc
    get:
      operationId: dumpprivkey
      parameters:
      - name: address
        in: query
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /dumpwallet:
    x-swagger-router-controller: rpc
    get:
      operationId: dumpwallet
      parameters:
      - name: filename
        in: query
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  Info:
    properties:
      version:
        type: number
      protocolversion:
        type: number
      walletversion:
        type: number
      balance:
        type: number
      blocks:
        type: number
      timeoffset:
        type: number
      connections:
        type: number
      proxy:
        type: string
      difficulty:
        type: number
      testnet:
        type: boolean
      keypoololdest:
        type: number
      keypoolsize:
        type: number
      unlocked_until:
        type: number
      paytxfee:
        type: number
      relayfee:
        type: number
      errors:
        type: string
  MiningInfo:
    properties:
      blocks:
        type: number
      currentblocksize:
        type: number
      currentblocktx:
        type: number
      difficulty:
        type: number
      errors:
        type: string
      genproclimit:
        type: number
      networkhashps:
        type: number
      pooledtx:
        type: number
      testnet:
        type: boolean
      chain:
        type: string
      generate:
        type: boolean
  PeerInfoResponse:
    type: array
    items:
      $ref: "#/definitions/PeerInfo"
  PeerInfo:
    properties:
      id:
        type: number
      addr:
        type: string
      addrlocal:
        type: string
      services:
        type: string
      relaytxes:
        type: boolean
      lastsend:
        type: number
      lastrecv:
        type: number
      bytessent:
        type: number
      bytesrecv:
        type: number
      conntime:
        type: number
      timeoffset:
        type: number
      pingtime:
        type: number
      minping:
        type: number
      version:
        type: number
      subver:
        type: string
      inbound:
        type: boolean
      startingheight:
        type: number
      banscore:
        type: number
      synced_headers:
        type: number
      synced_blocks:
        type: number
      inflight:
        type: array
        items:
          type: object
      whitelisted:
        type: boolean
      bytessent_per_msg:
        $ref: "#/definitions/ByteMessageInfo"
      bytesrecv_per_msg:
        $ref: "#/definitions/ByteMessageInfo"
  ByteMessageInfo:
    properties:
      addr:
        type: number
      getaddr:
        type: number
      getdata:
        type: number
      getheaders:
        type: number
      headers:
        type: number
      ping:
        type: number
      pong:
        type: number
      sendheaders:
        type: number
      verack:
        type: number
      version:
        type: number
  ValidateAddressResponse:
    properties:
      isvalid:
        type: boolean
      address:
        type: string
      ismine:
        type: boolean
      iswatchonly:
        type: boolean
      isscript:
        type: boolean
      pubkey:
        type: string
      iscompressed:
        type: boolean
      account:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Alias:
    properties:
      name:
        type: string
      value:
        type: string
      privatevalue:
        type: string
      txid:
        type: string
      address:
        type: string
      ismine:
        type: boolean
      lastupdate_height:
        type: number
      expires_in:
        type: number
      expires_on:
        type: number
      expired:
        type: boolean #returns 0/1
  AliasListEntry:
    required:
    - name
    - value
    - privatevalue
    - expires_in
    - expires_on
    - expired
    - pending
    properties:
      name:
        type: string
      value:
        type: string
      privatevalue:
        type: string
      expires_in:
        type: number
      expires_on:
        type: number
      expired:
        type: boolean #return 0/1
      pending:
        type: boolean #return 0/1
      txid:
        type: string #only returned with filter
  AliasHistoryEntry:
    properties:
      name:
        type: string
      aliastype:
        type: string
      value:
        type: string
      privatevalue:
        type: string
      txid:
        type: string
      address:
        type: string
      lastupdate_height:
        type: number
      expires_in:
        type: number
      expires_on:
        type: number
      expired:
        type: boolean #returns 0/1
  CertListEntry:
    properties:
      cert:
        type: string
      title:
        type: string
      data:
        type: string
      private:
        type: boolean #returns string Yes/No
      expires_in:
        type: number
      expires_on:
        type: number
      expired:
        type: boolean #returns 0/1
      address:
        type: string
      alias:
        type: string
  Cert:
    properties:
      cert:
        type: string
      txid:
        type: string
      height:
        type: number #returns string wrapped num
      title:
        type: string
      data:
        type: string
      private:
        type: boolean #returns string Yes/No
      ismine:
        type: boolean #returns string wrapped boolean
      address:
        type: string
      alias:
        type: string
      expires_in:
        type: number
      expires_on:
        type: number
      expired:
        type: boolean #returns 0/1
  CertHistoryEntry:
    properties:
      cert:
        type: string
      certtype:
        type: string
      private:
        type: boolean #returns string Yes/No
      data:
        type: string
      txid:
        type: string
      address:
        type: string
      alias:
        type: string
      expires_in:
        type: number
      expires_on:
        type: number
      expired:
        type: boolean #returns 0/1