swagger: "2.0"
info:
  version: "0.0.1"
  title: Syscoin API
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /rpc/getinfo:
    # binds a127 app logic to a route
    x-swagger-router-controller: getinfo
    get:
      description: Returns Syscoin server info to the caller
      # used as the method name of the controller
      operationId: getinfo
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetInfoResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  GetInfoResponse:
    required: [
        version,
        protocolversion,
        walletversion,
        balance,
        blocks,
        timeoffset,
        connections,
        proxy,
        difficulty,
        testnet,
        cakenet,
        keypoololdest,
        keypoolsize,
        paytxfee,
        mininput,
        errors
      ]
    properties:
      version:
        type: string
      protocolversion:
        type: integer
      walletversion:
        type: integer
      balance:
        type: number
      blocks:
        type: integer
      timeoffset:
        type: integer
      connections:
        type: integer
      proxy:
        type: string
      difficulty:
        type: number
      testnet:
        type: boolean
      cakenet:
        type: boolean
      keypoololdest:
        type: integer
      keypoolsize:
        type: integer
      paytxfee:
        type: number
      mininput:
        type: number
      errors:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
