swagger: "2.0"
info:
  version: "0.0.1"
  title: Syscoin API
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /rpc/getinfo:
    x-swagger-router-controller: coreController
    get:
      description: Returns Syscoin server info to the caller.
      operationId: getinfo
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/GetInfoResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /rpc/offerlist:
    x-swagger-router-controller: offerController
    get:
      description: Returns an array of Syscoin Offer objects contained in the wallet on the server to the caller.
      operationId: offerlist
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/OfferListResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /rpc/offernew:
    x-swagger-router-controller: offerController
    post:
      description: Creates a new Offer on the Syscoin blockchain making the item available for purchase by other Syscoin users and API consumers; this transaction incurs a fee.
      operationId: offernew
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/OfferNewResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /rpc/offerupdate:
    x-swagger-router-controller: offerController
    post:
      description: Updates an existing Offer on the Syscoin blockchain; this transaction incurs a fee.
      operationId: offerupdate
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/OfferUpdateResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /rpc/offerlink:
    x-swagger-router-controller: offerController
    get:
      description: Creates a new reseller Offer on the Syscoin blockchain based on an existing Offer already active on the blockchain. Reseller Offers are always linked to an existing Offer.
      operationId: offerlink
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/OfferLinkResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /rpc/offerrefund:
    x-swagger-router-controller: offerController
    get:
      description: Refunds a purchase of an Offer paid for on the Syscoin blockchain. It is recommended this command only be used in conjunction with resellers being linked to using the resller whitelist [INSERT INFO LINK HERE] feature. This command can only be executed by the root offer owner, resellers cannot perform refunds at this time but they can have the root offer owner perform a refund on their behalf.
      operationId: offerrefund
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/OfferRefundResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /rpc/offeraddwhitelist:
    x-swagger-router-controller: offerController
    get:
      description: Adds a Syscoin certificate GUID a wallet's reseller whitelist for a specific item. When using a whitelist, only addresses on the whitelist will be allowed to resell the Offer, but they are free to resell their own version of the Offer as well. This allows merchants to control which resllers (identified using Syscoin Addresses) are allowed to resell their Offers.
      operationId: offeraddwhitelist
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/OfferAddWhitelistResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /rpc/offerremovewhitelist:
    x-swagger-router-controller: offerController
    get:
      description: Removes a Syscoin certificate GUID to a wallet's reseller whitelist for a specific item. This removes a given merchants ability to resell a specific Offer from the current wallet.
      operationId: offerremovewhitelist
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/OfferRemoveWhitelistResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /rpc/whitelist:
    x-swagger-router-controller: offerController
    get:
      description: Returns an array of Syscoin whitelist entries containing (OBJECT || array of arrays??) which list the current whitelist addresses for a specific offer GUID.
      operationId: whitelist
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/WhitelistResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

# complex objects have schema definitions
definitions:
  GetInfoResponse:
    type: object
    required: [
        version,
        protocolversion,
        walletversion,
        balance,
        blocks,
        timeoffset,
        connections,
        proxy,
        difficulty,
        testnet,
        cakenet,
        keypoololdest,
        keypoolsize,
        paytxfee,
        mininput,
        errors
      ]
    properties:
      version:
        type: string
      protocolversion:
        type: integer
      walletversion:
        type: integer
      balance:
        type: number
      blocks:
        type: integer
      timeoffset:
        type: integer
      connections:
        type: integer
      proxy:
        type: string
      difficulty:
        type: number
      testnet:
        type: boolean
      cakenet:
        type: boolean
      keypoololdest:
        type: integer
      keypoolsize:
        type: integer
      paytxfee:
        type: number
      mininput:
        type: number
      errors:
        type: string

  OfferListResponse:
    type: array
    items:
      $ref: '#/definitions/Offer'
    
  Offer:
    type: object
    properties:
      id: 
        type: string
      txid: 
        type: string
      service_fee: 
        type: number
      address:
        type: string
      expires_in:
        type: integer
      expired:
        type: boolean
      payment_address:
        type: string
      category:
        type: string
      title:
        type: string
      quantity:
        type: integer
      price:
        type: number
      description:
        type: string
      accepts:
        type: array
        items:
          $ref: '#/definitions/OfferAccept'
        
  OfferAccept:
      type: object
      properties:
        id:
          type: string
        txid:
          type: string
        height:
          type: integer
        time:
          type: integer
        quantity:
          type: integer
        price:
          type: number
        paid:
          type: boolean
  
  OfferNewResponse:
    type: object
    properties:
     stub:
      type: string
  
  OfferUpdateResponse:
    type: object
    properties:
     stub:
      type: string
  
  OfferLinkResponse:
    type: object
    properties:
     stub:
      type: string
      
  
      
  Certificate:
    type: object
    properties:
     stub:
      type: string
  
  NameAlias:
    type: object
    properties:
     stub:
      type: string
  
  DataAlias:
    type: object
    properties:
     stub:
      type: string
        
  ErrorResponse:
    type: object
    required:
      - message
    properties:
      message:
        type: string
